{
 "title": "Logs",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "buttons",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{namespace=\"homeslice\", app=\"buttons\"} | json level=\"level\""
    }
   ]
  },
  {
   "title": "homebridge",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "{namespace=\"homeslice\", app=\"homebridge\"}"
    }
   ]
  },
  {
   "title": "switches",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "{namespace=\"homeslice\", app=\"switches\"}"
    }
   ]
  },
  {
   "title": "all homeslice",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "{namespace=\"homeslice\"}"
    }
   ]
  }
 ]
}