[project]
name = "flyte-simple"
version = "0.1.0"
description = "A simple Flyte project"
readme = "README.md"
requires-python = ">=3.9,<3.13"
dependencies = [
    "flytekit",
    "pydantic>=2.11.4",
    "tidalapi>=0.8.3",
]

[dependency-groups]
dev = [
    "mypy>=1.15.0",
]
