admin:
  # For GRPC endpoints you might want to use dns:///flyte.myexample.com
  endpoint: localhost:8089
  authType: Pkce
  insecure: true
console:
  endpoint: localhost:8088
logger:
  show-source: true
  level: 6
