fullnameOverride: flyte-binary
configuration:
  database:
    username: flyte
    host: postgres.flyte.svc.cluster.local
    dbname: flyte
  storage:
    type: minio
    metadataContainer: flyte #This is the default bucket created with Minio. Controlled by the MINIO_DEFAULT_BUCKETS env var in the local-flyte-resources.yaml manifest
    userDataContainer: flyte
    provider: s3
    providerConfig:
      s3:
        authType: "accesskey"
        endpoint: "http://minio.flyte.svc.cluster.local:9000"
        accessKey: "minio"
        secretKey: "%MINIO_PASSWORD%" #If you need to change this parameters, refer to the local-flyte-resources.yaml manifest and adjust the MINIO_ROOT_PASSWORD env var
        disableSSL: "true"
        secure: "false"
        v2Signing: "true"

  inlineSecretRef: flyte-binary-inline-config-secret
  inline:
    plugins:
      k8s:
        inject-finalizer: true
        default-env-vars:
          - FLYTE_AWS_ENDPOINT: "http://minio.flyte.svc.cluster.local:9000"
          - FLYTE_AWS_ACCESS_KEY_ID: "minio"
          - FLYTE_AWS_SECRET_ACCESS_KEY: "%MINIO_PASSWORD%" #Use the same value as the MINIO_ROOT_PASSWORD

    task_resources:
      defaults:
        cpu: 500m
        memory: 2Gi #change default requested resources and limits to fit your needs
      limits:
        cpu: 3000m
        memory: 4Gi

serviceAccount:
  create: true
