name: 'pipes'

on: [push]

env:
  REGISTRY: ghcr.io
  REPO_NAME: ${{ github.repository }}

jobs:
  apps:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
          cache-dependency-path: |
            app/backup_todoist/go.sum
            app/buttons/go.sum
            app/clocktime/go.sum
            app/switches/go.sum
      - name: Setup Go linters
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.55.0
      - name: setup Python
        uses: actions/setup-python@v3
      - name: lint
        run: cd apps && make lint
      - name: test
        run: cd apps && make test
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.REPO_NAME }}-clocktime
          tags: |
            type=sha,enable=true,priority=2000,prefix=gitsha-,suffix=,format=short
      - name: Build and push Docker images
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4

        # https://github.com/mikepartelow/homeslice/actions/runs/7840197203/job/21394404873?pr=14#step:10:283
        # https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs#example-using-a-single-dimension-matrix
        # https://github.com/docker/metadata-action?tab=readme-ov-file#outputs

        with:
          context: apps/clocktime
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  pulumi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup python
        uses: actions/setup-python@v3
      - name: lint
        run: cd pulumi && make lint
