name: 'pipes'

on: [push]
jobs:
  pipes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
          cache-dependency-path: |
            app/buttons/go.sum
            app/clocktime/go.sum
            app/switches/go.sum
      - name: Setup linters
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.55.0
      - name: lint
        run: cd apps && make lint
      - name: test
        run: cd apps && make test
