name: 'pipes'

on: [push]
jobs:
  go-apps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
          cache-dependency-path: |
            app/backup_todoist/go.sum
            app/buttons/go.sum
            app/clocktime/go.sum
            app/switches/go.sum
      - name: Setup Go linters
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.55.0
      - name: lint
        run: cd apps && make lint
      - name: test
        run: cd apps && make test
  python-apps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup python
        uses: actions/setup-python@v3
      - name: install linters
        run: pip install pylint black
      - name: lint
        run: cd python && black --check . && pylint "**/*.py"
  pulumi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup python
        uses: actions/setup-python@v3
      - name: install linters
        run: |
          pip install -r pulumi/requirements-lint.txt -r pulumi/requirements.txt
      - name: lint
        run: cd pulumi && black --check . && pylint "**/*.py"
